const chalk = require('chalk');
const packageJson = require('../../package.json');

module.exports = function manual() {
  console.log(chalk.bold.cyan('\n' + '='.repeat(80)));
  console.log(chalk.bold.cyan('                    lo - 资源仓库 CLI 手册'));
  console.log(chalk.bold.cyan('='.repeat(80)));

  console.log('\n' + chalk.bold('一、项目介绍'));
  console.log('─'.repeat(40));
  console.log(chalk.gray(`${packageJson.description}`));
  console.log(chalk.gray(`版本: ${packageJson.version}`));
  console.log('\n' + chalk.bold('功能特性:'));
  console.log('  📝  创建和管理 Markdown 笔记');
  console.log('  🔍  全文搜索资源');
  console.log('  🏷️  标签管理');
  console.log('  🔗  资源间建立链接关系');
  console.log('  📊  统计分析');
  console.log('  📁  资源导入/导出');
  console.log('  💾  自动备份');
  console.log('  📅  每日日记');

  console.log('\n' + chalk.bold('二、快速开始'));
  console.log('─'.repeat(40));
  console.log('  1. 初始化仓库');
  console.log('     lo init');
  console.log('\n  2. 创建第一篇笔记');
  console.log('     lo new "我的第一篇笔记"');
  console.log('\n  3. 查看资源列表');
  console.log('     lo list');
  console.log('\n  4. 搜索资源');
  console.log('     lo find "关键词"');

  console.log('\n' + chalk.bold('三、命令详解'));
  console.log('─'.repeat(40));

  console.log('\n' + chalk.bold.green('基础命令'));
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ ' + chalk.yellow('init') + '         初始化资源仓库                          │');
  console.log('│   用法: lo init [--path <路径>]                           │');
  console.log('│   作用: 在指定目录创建资源仓库结构，包括数据库和模板文件   │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('new') + '          创建新资源                            │');
  console.log('│   用法: lo new <标题> [--type <类型>] [--tags <标签>]     │');
  console.log('│         [--category <分类>] [--template <模板>]           │');
  console.log('│   类型: note, pdf, image, video, audio, html, text       │');
  console.log('│   作用: 创建新的 Markdown 笔记或其他类型资源              │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('import') + '       导入资源                            │');
  console.log('│   用法: lo import <路径> [--type <类型>]                 │');
  console.log('│   作用: 导入单个文件或整个目录到资源仓库                  │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('list') + '         列出所有资源                          │');
  console.log('│   用法: lo list [--type <类型>] [--tag <标签>]           │');
  console.log('│         [--category <分类>] [--limit <数量>]              │');
  console.log('│         [--format <table|json|list>]                     │');
  console.log('│   作用: 按条件筛选并列出资源                             │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('show') + '         查看资源内容                          │');
  console.log('│   用法: lo show <rid|路径> [--raw]                       │');
  console.log('│   作用: 显示资源的详细信息和内容，--raw 显示原始内容      │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('edit') + '         编辑资源                              │');
  console.log('│   用法: lo edit <rid|路径> [--editor <编辑器>]           │');
  console.log('│   作用: 使用指定编辑器打开资源文件                       │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('delete') + '       删除资源                              │');
  console.log('│   用法: lo delete <rid|路径> [--force] [--hard]          │');
  console.log('│   作用: 删除资源，--force 跳过确认，--hard 永久删除      │');
  console.log('└─────────────────────────────────────────────────────────────┘');

  console.log('\n' + chalk.bold.green('资源管理'));
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ ' + chalk.yellow('link') + '         建立资源链接                          │');
  console.log('│   用法: lo link <源> <目标> [--type <reference>]         │');
  console.log('│   作用: 在两个资源之间建立引用关系                       │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('move') + '         移动资源                              │');
  console.log('│   用法: lo move <rid|路径> <目标路径>                    │');
  console.log('│   作用: 将资源移动到指定目录                            │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('tag') + '          管理标签                              │');
  console.log('│   用法: lo tag <add|rm|list> <rid|路径> [标签]           │');
  console.log('│   作用: 添加、移除或列出资源的标签                      │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('sync') + '         同步资源                              │');
  console.log('│   用法: lo sync                                         │');
  console.log('│   作用: 扫描并同步文件系统中的资源到数据库               │');
  console.log('└─────────────────────────────────────────────────────────────┘');

  console.log('\n' + chalk.bold.green('搜索与查询'));
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ ' + chalk.yellow('find') + '         搜索资源                              │');
  console.log('│   用法: lo find <关键词> [--limit <数量>] [--type <类型>] │');
  console.log('│   作用: 全文搜索资源，支持模糊匹配                      │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('stats') + '        显示统计信息                            │');
  console.log('│   用法: lo stats [--today] [--week]                     │');
  console.log('│   作用: 显示资源仓库的统计数据，包括类型分布等           │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('index') + '        生成索引                              │');
  console.log('│   用法: lo index                                        │');
  console.log('│   作用: 生成 README.md 索引文件，包含所有资源列表        │');
  console.log('└─────────────────────────────────────────────────────────────┘');

  console.log('\n' + chalk.bold.green('其他命令'));
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ ' + chalk.yellow('daily') + '        创建今日日记                            │');
  console.log('│   用法: lo daily                                        │');
  console.log('│   作用: 创建包含今日完成、待办事项、想法记录的日记模板   │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('backup') + '       备份资源仓库                            │');
  console.log('│   用法: lo backup [--dest <目录>] [--compress]           │');
  console.log('│   作用: 备份整个资源仓库到指定目录                      │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('config') + '       管理配置                                │');
  console.log('│   用法: lo config <list|add|rm> [key] [dir]             │');
  console.log('│   作用: 查看、添加或删除配置项                          │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('help') + '         查看帮助                                │');
  console.log('│   用法: lo help                                         │');
  console.log('│   作用: 显示简洁的命令列表                              │');
  console.log('├─────────────────────────────────────────────────────────────┤');
  console.log('│ ' + chalk.yellow('manual') + '       查看完整手册                            │');
  console.log('│   用法: lo manual                                       │');
  console.log('│   作用: 显示本手册，包含所有命令的详细说明               │');
  console.log('└─────────────────────────────────────────────────────────────┘');

  console.log('\n' + chalk.bold('四、资源类型'));
  console.log('─'.repeat(40));
  console.log('  note    - Markdown 笔记（默认）');
  console.log('  pdf     - PDF 文件');
  console.log('  image   - 图片文件');
  console.log('  video   - 视频文件');
  console.log('  audio   - 音频文件');
  console.log('  html    - HTML 文件');
  console.log('  text    - 纯文本文件');

  console.log('\n' + chalk.bold('五、资源标识 (RID)'));
  console.log('─'.repeat(40));
  console.log('  每个资源都有唯一的 RID（Resource ID），格式为 res_xxx');
  console.log('  可以使用 RID 或文件路径来操作资源');

  console.log('\n' + chalk.bold('六、提示'));
  console.log('─'.repeat(40));
  console.log('  • 使用 lo <command> --help 查看特定命令的详细帮助');
  console.log('  • 在项目目录下使用 lo 命令，确保已执行 lo init');
  console.log('  • 资源存储在 resources/ 目录中，数据库在 .repo/ 目录');

  console.log('\n' + chalk.bold.cyan('='.repeat(80)));
  console.log(chalk.gray('                    lo - 让知识管理更简单'));
  console.log(chalk.bold.cyan('='.repeat(80)));
};